# Generated by Django 2.1.7 on 2019-03-25 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entiredata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=10, null=True)),
                ('category', models.CharField(max_length=10, null=True)),
                ('title', models.CharField(max_length=50, null=True)),
                ('link', models.CharField(max_length=30, null=True)),
                ('name', models.CharField(max_length=15, null=True)),
                ('period', models.CharField(max_length=19, null=True)),
                ('people', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
